name: 'Danger Zone'
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [master, main]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          cache: 'npm'
      - run: npm ci
      - run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
